language: php

php:
 - 7.2
 - 7.3
 - 7.4

before_script:
 - composer install --prefer-dist
 - echo 'xdebug.max_nesting_level=3000' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini

script:
 - ./vendor/bin/phpstan analyze --no-progress
 - ./vendor/bin/phpunit --bootstrap vendor/autoload.php --fail-on-warning tests/phpunit

cache:
 directories:
  - vendor

notifications:
 email: false
